name: Publish to npm Registry

on:
  pull_request:
    types: closed
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
      - name: Setup git repo
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: Version
        run: |
          npm run prerelease
          npm version minor --force -m "Version %s [build-skip]"
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Push release commit and tag to GitHub
        run: git push gh-origin HEAD:master --tags
